en este jupyter se va a analizar el dataset historic order demands

In [1]:
import pandas as pd

In [5]:
df_historic_order_demands = pd.read_excel("../dataset/df_historic_order_demand.xlsx")
df_historic_order_demands.head(50)

       cliente mes_anio  order_demand
0    Cliente_1  12-2020         857.0
1    Cliente_2  12-2020         941.0
2    Cliente_3  12-2020         878.0
3    Cliente_4  12-2020         949.0
4    Cliente_5  12-2020         932.0
5    Cliente_6  12-2020         873.0
6    Cliente_7  12-2020         895.0
7    Cliente_8  12-2020         942.0
8    Cliente_9  12-2020         856.0
9   Cliente_10  12-2020         923.0
10  Cliente_11  12-2020         861.0
11  Cliente_12  12-2020         926.0
12  Cliente_13  12-2020         944.0
13  Cliente_14  12-2020         904.0
14  Cliente_15  12-2020         891.0
15  Cliente_16  12-2020         942.0
16  Cliente_17  12-2020         906.0
17  Cliente_18  12-2020         887.0
18  Cliente_19  12-2020         852.0
19  Cliente_20  12-2020         923.0
20   Cliente_1  01-2021         768.0
21   Cliente_2  01-2021         756.0
22   Cliente_3  01-2021         752.0
23   Cliente_4  01-2021         716.0
24   Cliente_5  01-2021         738.0
25   Cliente_6  01-2021         769.0
26   Cliente_7  01-2021         702.0
27   Cliente_8  01-2021         718.0
28   Cliente_9  01-2021         726.0
29  Cliente_10  01-2021         704.0
30  Cliente_11  01-2021         767.0
31  Cliente_12  01-2021         679.0
32  Cliente_13  01-2021         696.0
33  Cliente_14  01-2021         715.0
34  Cliente_15  01-2021         735.0
35  Cliente_16  01-2021         727.0
36  Cliente_17  01-2021         697.0
37  Cliente_18  01-2021         688.0
38  Cliente_19  01-2021         711.0
39  Cliente_20  01-2021         757.0
40   Cliente_1  02-2021         635.0
41   Cliente_2  02-2021           NaN
42   Cliente_3  02-2021         637.0
43   Cliente_4  02-2021         594.0
44   Cliente_5  02-2021         605.0
45   Cliente_6  02-2021         578.0
46   Cliente_7  02-2021         585.0
47   Cliente_8  02-2021         599.0
48   Cliente_9  02-2021         578.0
49  Cliente_10  02-2021         620.0

In [7]:
df_historic_order_demands.isna().sum()

cliente          0
mes_anio         0
order_demand    48
dtype: int64

In [8]:
df_historic_order_demands.count()

cliente         980
mes_anio        980
order_demand    932
dtype: int64

In [9]:
df_historic_order_demands.dropna(inplace=True)

In [10]:
df_historic_order_demands.isna().sum()

cliente         0
mes_anio        0
order_demand    0
dtype: int64